version: '3'

services:
  db:
    image: postgres
    ports:
      - "5431:5432"
  redis:
     image: redis:3.2.6-alpine
     ports:
      - "6371:6379"
  uwsgi:
    build: .
    # command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "3000:3000"
    environment:
      DEBUG: 1
      SECRET_KEY: test_key
      REDIS_URL: "redis://redis:6379/0"
      DATABASE_URL: "postgres://postgres:postgres@db/postgres"
      ALLOWED_HOSTS: "*"
      PROJECT_TITLE: "TEST"
    depends_on:
      - db
      - redis
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - uwsgi