version: '3'

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
  redis:
     image: redis:3.2.6-alpine
     ports:
      - "6379:6379"
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis