# Generated by Django 2.0.4 on 2018-04-18 17:37

from django.db import migrations
import wot_user.models


class Migration(migrations.Migration):

    dependencies = [
        ('wot_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', wot_user.models.UserManager()),
            ],
        ),
    ]
