# Generated by Django 2.0.4 on 2018-04-18 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wot_api', '0002_auto_20180416_1137'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'get_latest_by': 'created'},
        ),
    ]
