# Generated by Django 2.0.4 on 2018-04-20 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wot_api', '0004_vehiclestatistics_vehiclestatisticsitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclestatisticsitem',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
