# Generated by Django 2.0.4 on 2018-04-20 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wot_api', '0005_auto_20180420_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiclestatistics',
            name='account_id',
        ),
        migrations.AddField(
            model_name='vehiclestatistics',
            name='account',
            field=models.ForeignKey(db_constraint=False, default=0, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='account_id'),
            preserve_default=False,
        ),
    ]
