# Generated by Django 2.0.4 on 2018-04-20 14:40

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wot_api', '0007_auto_20180420_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('tank_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('nation', models.CharField(max_length=200)),
                ('tier', models.SmallIntegerField()),
                ('description', models.TextField()),
                ('tag', models.CharField(max_length=200)),
                ('is_premium', models.BooleanField()),
                ('is_gift', models.BooleanField()),
                ('images', django.contrib.postgres.fields.jsonb.JSONField()),
                ('price_credit', models.IntegerField()),
                ('price_gold', models.IntegerField()),
            ],
        ),
    ]
