# Generated by Django 2.0.4 on 2018-04-24 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wot_api', '0011_vehiclestatisticitem_vehicle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expectedwn8values',
            name='vehicle',
            field=models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='expected', serialize=False, to='wot_api.Vehicle'),
        ),
    ]
