# Generated by Django 2.0.4 on 2018-04-24 09:39

from django.db import migrations

MINUTES = "minutes"


def create_wn8_task(apps, schema_editor):
    periodic_task_model = apps.get_model("django_celery_beat", "PeriodicTask")
    crontab_schedule_model = apps.get_model("django_celery_beat", "CrontabSchedule")
    interval_schedule_model = apps.get_model("django_celery_beat", "IntervalSchedule")

    daily_crontab, _ = crontab_schedule_model.objects.get_or_create(minute=0,
                                                                    hour=3,
                                                                    day_of_week="*",
                                                                    day_of_month="*",
                                                                    month_of_year="*")

    interval_15m, _ = interval_schedule_model.objects.get_or_create(every=15,
                                                                    period=MINUTES, )

    periodic_task_model.objects.get_or_create(name="wn8 expected values updated",
                                              task="wot_api.tasks.update_expected_values_wn8",
                                              crontab=daily_crontab)

    periodic_task_model.objects.get_or_create(name="update wot api vehicle data",
                                              task="wot_api.tasks.update_vehicles",
                                              crontab=daily_crontab)

    periodic_task_model.objects.get_or_create(name="update default clan",
                                              task="wot_api.tasks.update_default_clan",
                                              interval=interval_15m)


class Migration(migrations.Migration):
    dependencies = [
        ('wot_api', '0012_auto_20180424_0938'),
    ]

    operations = [
        migrations.RunPython(create_wn8_task, migrations.RunPython.noop),
    ]
