# Generated by Django 2.0.4 on 2018-04-25 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wot_api', '0013_wn8_update_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='first_of_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehiclestatistic',
            name='first_of_day',
            field=models.BooleanField(default=False),
        ),
    ]
