# Generated by Django 2.0.4 on 2018-04-25 10:43

from django.db import migrations, models
from django.db.models import F


def set_updated(apps, schema_editor):
    set_updated = apps.get_model("wot_api", "userinfo")
    set_updated.objects.update(updated=F('created'))


class Migration(migrations.Migration):
    dependencies = [
        ('wot_api', '0014_auto_20180425_0756'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(set_updated, migrations.RunPython.noop),
    ]
