# Generated by Django 2.0.4 on 2018-04-25 11:34

from django.db import migrations
from django.utils.timezone import now

MINUTES = "minutes"


def create_update(apps, schema_editor):
    periodic_task_model = apps.get_model("django_celery_beat", "PeriodicTask")
    periodics_task_model = apps.get_model("django_celery_beat", "PeriodicTasks")

    interval_schedule_model = apps.get_model("django_celery_beat", "IntervalSchedule")

    interval_1m, _ = interval_schedule_model.objects.get_or_create(every=1, period=MINUTES, )

    periodic_task_model.objects.get_or_create(name="update known users",
                                              task="wot_api.tasks.update_known_users",
                                              interval=interval_1m)

    # mark schedule as changed
    periodics_task_model.objects.update_or_create(ident=1, defaults={'last_update': now()})


class Migration(migrations.Migration):
    dependencies = [
        ('wot_api', '0015_userinfo_updated'),
    ]

    operations = [
        migrations.RunPython(create_update, migrations.RunPython.noop),
    ]
