# Generated by Django 2.0.4 on 2018-04-26 14:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wot_api', '0016_update_userinfos'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclestatistic',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
