# Generated by Django 2.0.6 on 2018-06-07 14:46

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wot_api', '0018_vehiclestatistic_userinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountStats',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('stat', django.contrib.postgres.fields.jsonb.JSONField()),
                ('account', models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, to_field='account_id')),
            ],
        ),
    ]
