# Generated by Django 2.0.6 on 2018-06-07 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wot_api', '0019_accountstats'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountstats',
            options={'get_latest_by': 'date', 'ordering': ['-date']},
        ),
    ]
