# Generated by Django 2.0.6 on 2018-06-15 15:08

from django.db import migrations


def create_update_scale_task(apps, schema_editor):
    periodic_task_model = apps.get_model("django_celery_beat", "PeriodicTask")
    crontab_schedule_model = apps.get_model("django_celery_beat", "CrontabSchedule")

    daily_crontab, _ = crontab_schedule_model.objects.get_or_create(minute=0,
                                                                    hour=3,
                                                                    day_of_week="*",
                                                                    day_of_month="*",
                                                                    month_of_year="*")

    periodic_task_model.objects.get_or_create(name="update xvm scales",
                                              task="wot_api.tasks.update_xvm_scales",
                                              crontab=daily_crontab)


class Migration(migrations.Migration):
    dependencies = [
        ('wot_api', '0020_auto_20180607_1525'),
    ]

    operations = [
        migrations.RunPython(create_update_scale_task, migrations.RunPython.noop),
    ]
